name: Releases

on: 
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/*"
        tag: notCool
    - name: make build directory
      run: mkdir build
    - name: build for windows
      run: GOOS=windows GOARCH=amd64 go build -o bin/gotunnelme-testcasego-windows.exe
    - name: build for linux
      run: go build -o bin/gotunnelme-testcasego-linux
    - name: create releases archive
      run: zip -r binaries.zip bin
    
